version: "3"

services:
    db:
        image: mariadb:10.4.31
        platform: linux/x86_64
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MARIADB_DATABASE: db
            MARIADB_PASSWORD: db
            MARIADB_USER: db
            MARIADB_ROOT_PASSWORD: db
        ports:
            - "3306:3306"
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
        networks:
            - symfony_app
        command: >
            sh -c "bin/console doctrine:migrations:migrate && bin/console doctrine:fixtures:load -q && php-fpm"
        depends_on:
            - db
            - nginx
            - redis

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
        ports:
            - "80:80"
        networks:
            - symfony_app
        env_file:
            - .env.nginx

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_app:/root/redis
        environment:
            - REDIS_USERNAME=redis
            - REDIS_PASSWORD=redis
            - REDIS_PORT=6379
            - REDIS_DATABASE=0
        networks:
            - symfony_app

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=docker:redis:6379:0:redis:redis
        ports:
            - "8081:8081"
        networks:
            - symfony_app
        depends_on:
            - redis

volumes:
    db_app:
    redis_app:

networks:
    symfony_app:
